# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCrearusuarioincompleto():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_crearusuarioincompleto(self):
    self.driver.get("http://localhost/Sistema_venta_basico-master/sistema/")
    self.driver.set_window_size(1050, 708)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(9) span").click()
    self.driver.find_element(By.LINK_TEXT, "Nuevo Usuario").click()
    self.driver.find_element(By.ID, "correo").click()
    self.driver.find_element(By.ID, "correo").send_keys("francisco@gmail.com")
    self.driver.find_element(By.ID, "usuario").click()
    self.driver.find_element(By.ID, "usuario").send_keys("francisco21")
    self.driver.find_element(By.ID, "rol").click()
    dropdown = self.driver.find_element(By.ID, "rol")
    dropdown.find_element(By.XPATH, "//option[. = 'Vendedor']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(6)").click()
    self.driver.execute_script("window.scrollTo(0,106)")
  
