# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAgregarproveedor():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_agregarproveedor(self):
    self.driver.get("http://localhost/Sistema_venta_basico-master/sistema/index.php")
    self.driver.set_window_size(1050, 708)
    self.driver.find_element(By.LINK_TEXT, "Proveedor").click()
    self.driver.find_element(By.LINK_TEXT, "Nuevo Proveedor").click()
    self.driver.find_element(By.ID, "nombre").click()
    self.driver.find_element(By.ID, "nombre").send_keys("Cecompsa")
    self.driver.find_element(By.ID, "contacto").click()
    self.driver.find_element(By.ID, "contacto").send_keys("40112587")
    self.driver.find_element(By.ID, "telefono").click()
    self.driver.find_element(By.ID, "telefono").send_keys("822885674")
    self.driver.find_element(By.ID, "direcion").click()
    self.driver.find_element(By.ID, "direcion").send_keys("La caleta")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
  
