# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestActualizarproducto():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_actualizarproducto(self):
    self.driver.get("http://localhost/Sistema_venta_basico-master/")
    self.driver.set_window_size(1050, 708)
    self.driver.find_element(By.NAME, "usuario").click()
    self.driver.find_element(By.NAME, "usuario").send_keys("admin")
    self.driver.find_element(By.NAME, "clave").click()
    self.driver.find_element(By.NAME, "clave").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Productos").click()
    self.driver.find_element(By.CSS_SELECTOR, "#collapseUtilities .collapse-item:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".even:nth-child(2) .btn-success > .svg-inline--fa").click()
    self.driver.find_element(By.ID, "precio").click()
    self.driver.find_element(By.ID, "precio").send_keys("2800.00")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
  
