# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAgregarproducto():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_agregarproducto(self):
    self.driver.get("http://localhost/Sistema_venta_basico-master/sistema/index.php")
    self.driver.set_window_size(1050, 708)
    self.driver.find_element(By.LINK_TEXT, "Productos").click()
    self.driver.find_element(By.LINK_TEXT, "Nuevo Producto").click()
    self.driver.find_element(By.ID, "producto").click()
    self.driver.find_element(By.ID, "producto").send_keys("Cargador")
    self.driver.find_element(By.ID, "precio").click()
    self.driver.find_element(By.ID, "precio").send_keys("650")
    self.driver.find_element(By.ID, "cantidad").click()
    self.driver.find_element(By.ID, "cantidad").send_keys("130")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
  
